#!/bin/sh
# <!-- **************************************  -->
# <!-- Don't Remove this Disclaimer            -->
# <!-- **************************************  -->
echo
echo "*****************************************"
echo "*         Uninstall DD_RSS              *"
echo "*****************************************"

EXTDIR="/usr/lib/enigma2/python/Plugins/Extensions/DD_RSS"
VARX="/var/ddRSS"
if [ -d "$EXTDIR" ]; then
   rm -rf "$EXTDIR" > /dev/null 2>&1
   rm -rf "$VARX" > /dev/null 2>&1
fi

echo "*****************************************"
echo "*          ....done                     *"
echo "*****************************************"
exit 0


